---
title: "암호화폐 모형진단 및 시각화"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
  runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(jsonlite)
library(shiny)
library(tm)
library(PerformanceAnalytics)
library(corrplot)
library(xts)
library(TTR)
library(dplyr)
library(shinyjs)
library(rlang)
library(stringr)
library(forecast)

marketname <- fromJSON("https://api.upbit.com/v1/market/all?isDetails=false") %>% select(market,korean_name)
marketname <- marketname %>% filter(str_detect(marketname$market,"KRW")==TRUE)
no_data <- read.csv("total_info.csv")
xt_data <- no_data
xt_data$candle_date_time_utc <- xt_data$candle_date_time_utc%>% as.character() %>% as.Date(format='%y%m%d')


```

Sidebar {.sidebar}
=====================================
```{r}

selectInput('name','마켓명',marketname$market)
numericInput("AR","AR",value = 0,min = 0)
numericInput("MA","MA",value = 0,min = 0)
numericInput("FOREDAY","예측 일수",value = 1,min = 0)

```

Auto.ARIMA를 이용한 측정
=====================================
## ROW {data-height="150"}
### 예측수익률 및 ARIMA 모델 계수

```{r}

selectMarket <- reactive({
  subset(xt_data, market == input$name)
})

selectMarket2 <- reactive({
  subset(no_data, market == input$name)
})

renderTable({
  a <- list()
  selectMarket_D <- selectMarket() %>% select(candle_date_time_utc, trade_price) %>% as.xts()
  model <- forecast::auto.arima(selectMarket_D)
  a <- rbind(a, list(market = input$name, ar = length(model$model$phi), i = length(model$model$Delta), ma = length(model$model$theta)))
  fore <- forecast::forecast(auto.arima(selectMarket_D), h = 5)
  selectMarket2_D <- selectMarket2()[1,] %>% select(market, trade_price) %>% mutate(forec = fore$mean[5], returns = (forec - trade_price) / (trade_price) * 100)
  selectMarket2_D <- merge(selectMarket2_D, a)
  df <- selectMarket2_D
})
```

## ROW {data-height="800"}
### ARIMA모델 모형진단
```{r}
selectMarket <- reactive({
  subset(xt_data, market == input$name)
})

renderPlot({
  selectMarket_D <- selectMarket() %>% select(candle_date_time_utc, trade_price) %>% as.xts()
  model <- forecast::auto.arima(selectMarket_D)
  model <-forecast::Arima(selectMarket_D,c(length(model$model$phi),length(model$model$Delta),length(model$model$theta)))
  stats::tsdiag(model)
})
```

ARIMA계수 직접 찾아보기
=====================================
## ROW {data-height="150"}
### 예측수익률 및 ARIMA 모델 계수

```{r}

selectMarket <- reactive({
  subset(xt_data, market == input$name)
})

selectMarket2 <- reactive({
  subset(no_data, market == input$name)
})

renderTable({
  a <- list()
  selectMarket_D <- selectMarket() %>% select(candle_date_time_utc, trade_price) %>% as.xts()
  model <- forecast::auto.arima(selectMarket_D)
  a <- rbind(a, list(market = input$name, ar = length(model$model$phi), i = length(model$model$Delta), ma = length(model$model$theta)))
  fore <- forecast::forecast(auto.arima(selectMarket_D), h = 5)
  selectMarket2_A <- selectMarket2()[1,] %>% select(market, trade_price) %>% mutate(forec = fore$mean[5], returns = (forec - trade_price) / (trade_price) * 100)
  selectMarket2_A <- merge(selectMarket2_A, a)
  df <- selectMarket2_A
})
```
## ROW {data-height="500"}
### 차분데이터 ACF모델(MA모델 찾기 위해선 맨 앞부터 선안에 들어간 그래프 수 측정)
```{r}
selectMarket=reactive({
  subset(xt_data,market==input$name)
})
renderPlot({
  MA <- selectMarket() %>%select(candle_date_time_utc,trade_price) %>% as.xts() %>% diff() 
  MA <- MA[2:nrow(MA),]
  acf(MA)
})
```
## ROW {data-height="500"}
### 차분데이터 PACF모델(AR모델 찾기 위해선 맨 앞부터 선안에 들어간 그래프 수 측정)
```{r}
selectMarket=reactive({
  subset(xt_data,market==input$name)
})
renderPlot({
  MA <- selectMarket() %>%select(candle_date_time_utc,trade_price) %>% as.xts() %>% diff()
  MA <- MA[2:nrow(MA),]
  pacf(MA)
})
```
ARIMA계수 직접 찾아보기
=====================================
## ROW {data-height="150"}
### 직접 입력한 ARMA계수로 변환치 확인
```{r}
selectMarket <- reactive({
  subset(xt_data, market == input$name)
})

selectMarket2 <- reactive({
  subset(no_data, market == input$name)
})

returns <- reactive({
  selectMarket_a <- selectMarket() %>% select(candle_date_time_utc, trade_price) %>% as.xts()
  model <- forecast::auto.arima(selectMarket_a)
  
  fore_a <- forecast::forecast(Arima(selectMarket_a,c(input$AR,length(model$model$Delta),input$MA)), h = input$FOREDAY)
  
  selectMarket2_a <- selectMarket2()[1,] %>% select(market, trade_price) %>% mutate(forec = fore_a$mean[input$FOREDAY], returns = (forec - trade_price) / trade_price * 100)
  
  df <- data.frame(
    market = input$name,
    trade_price = selectMarket2_a$trade_price,
    forec = selectMarket2_a$forec,
    returns = selectMarket2_a$returns,
    ar = input$AR,
    i = length(model$model$Delta),
    ma = input$MA
  )
  
  df
})
renderTable({
  df <- returns()
  df
})

```

## ROW {data-height="750"}
### 예측 시각화
```{r}
selectMarket <- reactive({
  subset(xt_data, market == input$name)
})

selectMarket2 <- reactive({
  subset(no_data, market == input$name)
})

fore <- reactive({
  selectMarket_a <- selectMarket() %>% select(candle_date_time_utc, trade_price) %>% as.xts()
  model <- forecast::auto.arima(selectMarket_a)
  
  fore_a <- forecast::forecast(Arima(selectMarket_a,c(input$AR,length(model$model$Delta),input$MA)), h = input$FOREDAY)
})
renderPlot({
  plot(fore(),ann=FALSE)
  title(main=marketname$korean_name[marketname$market==input$name])
  
})
```
